In [3]:
import numpy as np

# 1次元配列

In [10]:
a = np.array([1, 2, 3])

In [6]:
a

array([1, 2, 3])

In [7]:
print(a)

[1 2 3]


In [8]:
type(a)

numpy.ndarray

In [9]:
a.shape

(3,)

# 2次元配列

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape

(2, 3)

## 変形(reshape)

In [14]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [16]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
# 元に戻す
c3 = c2.ravel() # 参照を返す
c3

array([0, 1, 2, 3, 4, 5])

In [19]:
c4 = c2.flatten() # copyを返す
c4

array([0, 1, 2, 3, 4, 5])

# データ型

In [21]:
a.dtype

dtype('int64')

In [22]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [23]:
d.dtype

dtype('int16')

In [24]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

# インデックスとスライス

In [26]:
a

array([1, 2, 3])

In [27]:
a[0]

np.int64(1)

In [28]:
a[1:]

array([2, 3])

In [29]:
a[-1]

np.int64(3)

In [30]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
b[0]

array([1, 2, 3])

In [32]:
b[1, 0]

np.int64(4)

In [33]:
b[:, 2]

array([3, 6])

In [34]:
b[1, :]

array([4, 5, 6])

In [35]:
b[0, 1:]

array([2, 3])

In [36]:
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

## データ再代入

In [37]:
a

array([1, 2, 3])

In [42]:
a[2] = 4
a

array([1, 2, 4])

In [40]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [43]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

## 深いコピー

In [44]:
a

array([1, 2, 4])

In [45]:
a1 = a
a1

array([1, 2, 4])

In [46]:
a1[1] = 5
a1

array([1, 5, 4])

In [47]:
a

array([1, 5, 4])

In [48]:
a2 = a.copy()
a2

array([1, 5, 4])

In [49]:
a2[0] = 6
a2

array([6, 5, 4])

In [50]:
a

array([1, 5, 4])

In [51]:
# ravelメソッドとflattenメソッド
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
c3 = c2.ravel() # 参照（浅いコピー）
c4 = c2.flatten() # コピー（深いコピー）
c3[0] = 6
c4[1] = 7

In [53]:
c3

array([6, 1, 2, 3, 4, 5])

In [54]:
c4

array([0, 7, 2, 3, 4, 5])

In [55]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [59]:
# Python標準のリストは、スライスした結果はコピー（深いコピー）
p_list1 = [0, 1]
p_list2 = p_list1[:]
p_list2[0] = 2

print(p_list1)
print(p_list2)

[0, 1]
[2, 1]


In [58]:
# NumPyのndarrayでのスライスした結果は参照
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array2[0] = 2

print(np_array1)
print(np_array2)

[2 1]
[2 1]


# 数列を返す(arange)

In [60]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## 乱数

In [64]:
f = np.random.random((3, 2))
f

array([[0.14613255, 0.22059337],
       [0.95895476, 0.83156506],
       [0.66170823, 0.51394318]])

In [65]:
np.random.seed(123)
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [66]:
np.random.seed(123)
np.random.rand(4,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [67]:
np.random.seed(123)
np.random.randint(1, 10)

3

In [68]:
np.random.seed(123)
np.random.randint(1, 10, (3, 3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [74]:
np.random.seed(123)
# 0.0以上、5.0未満の2x3の行列の2次元配列
np.random.uniform(0.0, 5.0, size=(2, 3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [71]:
np.random.seed(123)
np.random.uniform(size=(4, 3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [73]:
np.random.seed(123)
# 標準正規分布から4x2の行列の2次元配列を得る
np.random.randn(4, 2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [75]:
np.random.seed(123)
np.random.normal(50, 10, size=(3, 3))

array([[39.14369397, 59.97345447, 52.82978498],
       [34.93705286, 44.21399748, 66.51436537],
       [25.73320757, 45.71087371, 62.65936259]])