In [3]:
import numpy as np

# 1次元配列

In [10]:
a = np.array([1, 2, 3])

In [6]:
a

array([1, 2, 3])

In [7]:
print(a)

[1 2 3]


In [8]:
type(a)

numpy.ndarray

In [9]:
a.shape

(3,)

# 2次元配列

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape

(2, 3)

## 変形(reshape)

In [14]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [16]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
# 元に戻す
c3 = c2.ravel() # 参照を返す
c3

array([0, 1, 2, 3, 4, 5])

In [19]:
c4 = c2.flatten() # copyを返す
c4

array([0, 1, 2, 3, 4, 5])

# データ型

In [21]:
a.dtype

dtype('int64')

In [22]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [23]:
d.dtype

dtype('int16')

In [24]:
d.astype(np.float16)

array([1., 2.], dtype=float16)