In [1]:
import numpy as np

# 1次元配列

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

# 2次元配列

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

## 変形(reshape)

In [10]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [11]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
# 元に戻す
c3 = c2.ravel() # 参照を返す
c3

array([0, 1, 2, 3, 4, 5])

In [13]:
c4 = c2.flatten() # copyを返す
c4

array([0, 1, 2, 3, 4, 5])

# データ型

In [14]:
a.dtype

dtype('int64')

In [15]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [16]:
d.dtype

dtype('int16')

In [17]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

# インデックスとスライス

In [18]:
a

array([1, 2, 3])

In [19]:
a[0]

np.int64(1)

In [20]:
a[1:]

array([2, 3])

In [21]:
a[-1]

np.int64(3)

In [22]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b[0]

array([1, 2, 3])

In [24]:
b[1, 0]

np.int64(4)

In [25]:
b[:, 2]

array([3, 6])

In [26]:
b[1, :]

array([4, 5, 6])

In [27]:
b[0, 1:]

array([2, 3])

In [28]:
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

## データ再代入

In [29]:
a

array([1, 2, 3])

In [30]:
a[2] = 4
a

array([1, 2, 4])

In [31]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [33]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

## 深いコピー

In [34]:
a

array([1, 2, 4])

In [35]:
a1 = a
a1

array([1, 2, 4])

In [36]:
a1[1] = 5
a1

array([1, 5, 4])

In [37]:
a

array([1, 5, 4])

In [38]:
a2 = a.copy()
a2

array([1, 5, 4])

In [39]:
a2[0] = 6
a2

array([6, 5, 4])

In [40]:
a

array([1, 5, 4])

In [41]:
# ravelメソッドとflattenメソッド
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
c3 = c2.ravel() # 参照（浅いコピー）
c4 = c2.flatten() # コピー（深いコピー）
c3[0] = 6
c4[1] = 7

In [43]:
c3

array([6, 1, 2, 3, 4, 5])

In [44]:
c4

array([0, 7, 2, 3, 4, 5])

In [45]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [46]:
# Python標準のリストは、スライスした結果はコピー（深いコピー）
p_list1 = [0, 1]
p_list2 = p_list1[:]
p_list2[0] = 2

print(p_list1)
print(p_list2)

[0, 1]
[2, 1]


In [47]:
# NumPyのndarrayでのスライスした結果は参照
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array2[0] = 2

print(np_array1)
print(np_array2)

[2 1]
[2 1]


# 数列を返す(arange)

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## 乱数

In [51]:
f = np.random.random((3, 2))
f

array([[0.83918398, 0.82494981],
       [0.39333989, 0.08189499],
       [0.69166097, 0.05601435]])

In [52]:
np.random.seed(123)
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [53]:
np.random.seed(123)
np.random.rand(4,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [54]:
np.random.seed(123)
np.random.randint(1, 10)

3

In [55]:
np.random.seed(123)
np.random.randint(1, 10, (3, 3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [56]:
np.random.seed(123)
# 0.0以上、5.0未満の2x3の行列の2次元配列
np.random.uniform(0.0, 5.0, size=(2, 3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [57]:
np.random.seed(123)
np.random.uniform(size=(4, 3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [58]:
np.random.seed(123)
# 標準正規分布から4x2の行列の2次元配列を得る
np.random.randn(4, 2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [59]:
np.random.seed(123)
np.random.normal(50, 10, size=(3, 3))

array([[39.14369397, 59.97345447, 52.82978498],
       [34.93705286, 44.21399748, 66.51436537],
       [25.73320757, 45.71087371, 62.65936259]])

## 同じ要素の数列を作る

In [60]:
np.zeros(3)

array([0., 0., 0.])

In [61]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.ones(2)

array([1., 1.])

In [63]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 単位行列 

In [64]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 指定値で埋める

In [65]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [66]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [68]:
np.nan

nan

In [71]:
# ndarrayでは同じデータ型のみが格納できる。欠損値をNoneや空文字にするとエラーになる都合上、特殊な定数としてnp.nanは使われる
type(np.nan)

float

In [72]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

## 範囲指定で均等割データを作る

In [73]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [74]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

### 要素間の差分

In [75]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

### 連結

In [76]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [77]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [78]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [79]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [81]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [84]:
# 横方向(horizontal)に広げるイメージ
np.hstack([b, b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [85]:
b2 = np.array([30, 60, 45])
b2

array([30, 60, 45])

In [88]:
# 縦方向（vertical)に広げるイメージ
b3 = np.vstack([b, b2])
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

## 分割

In [89]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [ ]:
# 列方向に分割する
first, second = np.hsplit(b3, [2])

In [91]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [92]:
second

array([[ 8],
       [ 8],
       [45]])

In [98]:
# 行方向に分割する
first1, second1 = np.vsplit(b3, [2])

In [95]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [97]:
second1

array([[30, 60, 45]])

## 転置

In [99]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [100]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

## 次元追加

In [101]:
a

array([1, 5, 4])

In [102]:
a[np.newaxis, :]

array([[1, 5, 4]])

In [103]:
a[:, np.newaxis]

array([[1],
       [5],
       [4]])

In [105]:
# reshapeを使った方法
a.reshape((3, 1))

array([[1],
       [5],
       [4]])

## グリッドデータの生成

In [106]:
m = np.arange(0, 4)
m

array([0, 1, 2, 3])

In [107]:
n = np.arange(4, 7)
n

array([4, 5, 6])

In [108]:
xx, yy = np.meshgrid(m, n)

In [109]:
print(xx)
print(yy)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


## NumPyの各機能

In [110]:
import numpy as np

In [112]:
a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)

print(f'a : {a}')
print(f'b : {b}')
print(f'c : {c}')
print(f'd : {d}')
print(f'e : {e}')

a : [0 1 2]
b : [[-3 -2 -1]
 [ 0  1  2]]
c : [[1 2 3]
 [4 5 6]]
d : [[0 1]
 [2 3]
 [4 5]]
e : [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [116]:
print(f'a : {a.shape}')
print(f'b : {b.shape}')
print(f'c : {c.shape}')
print(f'd : {d.shape}')
print(f'e : {e.shape}')

a : (3,)
b : (2, 3)
c : (2, 3)
d : (3, 2)
e : (10,)


## ユニバーサルファンクション

In [120]:
# 通常のPythonでの実装
li = [[-3, -2, -1],
      [0, 1, 2]]
new = []
for i, j in enumerate(li):
  new.append([])
  for k in j:
    new[i].append(abs(k))

In [121]:
new

[[3, 2, 1], [0, 1, 2]]

In [124]:
# 内部要素にまとめて絶対値を取得する関数を適用する
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [126]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [127]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [128]:
np.log(a)

/var/folders/yn/rx1lyty16dnfrgwgqmk04h4m0000gn/T/ipykernel_24846/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

In [129]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [130]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

## ブロードキャスト

配列の内部データに直接演算などが行える機能

In [131]:
a

array([0, 1, 2])

In [132]:
a + 10

array([10, 11, 12])

In [133]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [135]:
# 次元が違う配列同士の演算
a + b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [137]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [139]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [140]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
c - np.mean(c)
(c - np.mean(c)) ** 2

array([[6.25, 2.25, 0.25],
       [0.25, 2.25, 6.25]])

In [143]:
b * 2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [144]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [149]:
b - a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [150]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [151]:
a / c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [153]:
# 0で割る
c / a

/var/folders/yn/rx1lyty16dnfrgwgqmk04h4m0000gn/T/ipykernel_24846/910504001.py:2: RuntimeWarning: divide by zero encountered in divide
  c / a


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [155]:
# 1e-6 = 10の-6乗
c / (a+1e-6)

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

## ドット積

In [156]:
a

array([0, 1, 2])

In [157]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [158]:
np.dot(b, a)

array([-4,  5])

In [159]:
b @ a

array([-4,  5])

In [160]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [161]:
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [163]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [164]:
d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

## 判定・論理値

In [166]:
a > 1

array([False, False,  True])

In [168]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [172]:
# Trueが1, Falseが0と扱われるのを利用する
np.count_nonzero(b > 0)

np.int64(2)

In [ ]:
# Trueが1, Falseが0と扱われるのを利用する
np.sum(b > 0)

np.int64(2)

In [173]:
np.any(b > 0)

np.True_

In [174]:
np.all(b > 0)

np.False_

In [176]:
b[b > 0]

array([1, 2])

In [179]:
b == c

array([[False, False, False],
       [False, False, False]])

In [186]:
# 形状の合わない配列同士の比較は、ブロードキャストによって形状をあわせてから比較される
a == b

array([[False, False, False],
       [ True,  True,  True]])

In [187]:
(b == c) | (a == b)

array([[False, False, False],
       [ True,  True,  True]])

In [188]:
b[(b == c) | (a == b)]

array([0, 1, 2])

In [191]:
# すべての要素が同じか（誤差の範囲を許す）
np.allclose(b, c)

False

In [192]:
np.allclose(b, c, atol=10)

True

## 関数とメソッド

In [193]:
np.sum(a)

np.int64(3)

In [194]:
a.sum()

np.int64(3)