# 前処理

In [2]:
import numpy as np
import pandas as pd

In [3]:
# サンプルのデータセット
df = pd.DataFrame(
  {
    'A': [1, np.nan, 3, 4, 5],
    'B': [6, 7, 8, np.nan, 10],
    'C': [11, 12, 13, 14, 15]
  }
)
df

,A,B,C
0,1.0,6.0,11
1,NaN,7.0,12
2,3.0,8.0,13
3,4.0,NaN,14
4,5.0,10.0,15


In [4]:
df.isnull()

,A,B,C
0,False,False,False
1,True,False,False
2,False,False,False
3,False,True,False
4,False,False,False


In [7]:
# 欠損値の補完
from sklearn.impute import SimpleImputer
# 平均値で欠損値を補完するインスタンスを作成する
imp = SimpleImputer(strategy='mean')
# 欠損値を補完
imp.fit(df)
imp.transform(df)

array([[ 1.  ,  6.  , 11.  ],
       [ 3.25,  7.  , 12.  ],
       [ 3.  ,  8.  , 13.  ],
       [ 4.  ,  7.75, 14.  ],
       [ 5.  , 10.  , 15.  ]])

In [8]:
import pandas as pd
df = pd.DataFrame(
  {
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'a', 'b', 'c']
  }
)
df

,A,B
0,1,a
1,2,b
2,3,a
3,4,b
4,5,c


## カテゴリ変数のエンコーディング

In [9]:
from sklearn.preprocessing import LabelEncoder
# ラベルエンコーダーのインスタンスを生成
le = LabelEncoder()
le.fit(df['B'])
le.transform(df['B'])

array([0, 1, 0, 1, 2])

In [11]:
# 元の値を確認
le.classes_

array(['a', 'b', 'c'], dtype=object)

## One-hotエンコーディング

In [12]:
df

,A,B
0,1,a
1,2,b
2,3,a
3,4,b
4,5,c


In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# B列（1番目のインデックス）にのみOneHotEncoderを適用
# remainder='passthrough' で他の列を残す
ct = ColumnTransformer(
    transformers=[("onehot", OneHotEncoder(), ['B'])],
    remainder='passthrough'
)

# 直接変換
df_ohe_array = ct.fit_transform(df)
df_ohe_array

array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [1., 0., 0., 3.],
       [0., 1., 0., 4.],
       [0., 0., 1., 5.]])

# 特徴量の正規化

In [16]:
import pandas as pd

df = pd.DataFrame(
  {
    'A': [1, 2, 3, 4, 5],
    'B': [100, 200, 400, 500, 800]
  }
)

df

,A,B
0,1,100
1,2,200
2,3,400
3,4,500
4,5,800


In [17]:
df['A'].mean()

np.float64(3.0)

In [21]:
df['A'].std(ddof=0)

np.float64(1.4142135623730951)

In [22]:
# 分散正規化
from sklearn.preprocessing import StandardScaler
# 分散正規化のインスタンスを生成
stdsc = StandardScaler()
# 分散正規化を実行
stdsc.fit(df)
stdsc.transform(df)

array([[-1.41421356, -1.22474487],
       [-0.70710678, -0.81649658],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.40824829],
       [ 1.41421356,  1.63299316]])

In [23]:
# 最小最大正規化
from sklearn.preprocessing import MinMaxScaler
# 最小最大正規化のインスタンスを生成
mmsc = MinMaxScaler()
# 最小最大正規化を実行
mmsc.fit(df)
mmsc.transform(df)

array([[0.        , 0.        ],
       [0.25      , 0.14285714],
       [0.5       , 0.42857143],
       [0.75      , 0.57142857],
       [1.        , 1.        ]])